# Module 9: Integrating Polars into the DataScience Workflow

In [1]:
import polars as pl

In [2]:
import matplotlib.pyplot as plt
from lightgbm import LGBMRegressor
from sklearn.metrics import mean_absolute_error

In [3]:
zone_columns_rename_mapping = {
    "LocationID": "location_id",
    "Borough": "borough",
    "Zone": "zone",
}

zones_df = (
    pl.read_parquet("./../data/taxi_zone_lookup.parquet")
).rename(zone_columns_rename_mapping)

zones_df.head()

shape: (5, 4)
┌─────────────┬───────────────┬─────────────────────────┬──────────────┐
│ location_id ┆ borough       ┆ zone                    ┆ service_zone │
│ ---         ┆ ---           ┆ ---                     ┆ ---          │
│ i32         ┆ str           ┆ str                     ┆ str          │
╞═════════════╪═══════════════╪═════════════════════════╪══════════════╡
│ 1           ┆ EWR           ┆ Newark Airport          ┆ EWR          │
│ 2           ┆ Queens        ┆ Jamaica Bay             ┆ Boro Zone    │
│ 3           ┆ Bronx         ┆ Allerton/Pelham Gardens ┆ Boro Zone    │
│ 4           ┆ Manhattan     ┆ Alphabet City           ┆ Yellow Zone  │
│ 5           ┆ Staten Island ┆ Arden Heights           ┆ Boro Zone    │
└─────────────┴───────────────┴─────────────────────────┴──────────────┘

In [4]:
yellow_rides_column_rename_mapping = {
    "VendorID": "vendor_id",
    "RatecodeID": "rate_code_id",
    "PULocationID": "pickup_location_id",
    "DOLocationID": "dropoff_location_id",
    "Airport_fee": "airport_fee",
}

zones_df_columns = ["borough", "zone", "service_zone"]
rides_df_raw = (
    pl.read_parquet("./../data/yellow_tripdata_2024-*.parquet")
    .rename(yellow_rides_column_rename_mapping)
    .join(zones_df, left_on="pickup_location_id", right_on="location_id")
    .rename({zones_df_column: f"pu_{zones_df_column}" for zones_df_column in zones_df_columns})
    .join(zones_df, left_on="dropoff_location_id", right_on="location_id")
    .rename({zones_df_column: f"do_{zones_df_column}" for zones_df_column in zones_df_columns})
)

rides_df_raw.head()

shape: (5, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ vendor_id ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ pu_servic ┆ do_boroug ┆ do_zone   ┆ do_servi │
│ ---       ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ e_zone    ┆ h         ┆ ---       ┆ ce_zone  │
│ i32       ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ ---       ┆ ---       ┆ i64       ┆   ┆ str       ┆ str       ┆           ┆ str      │
│           ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2         ┆ 2024-02-0 ┆ 2024-02-0 ┆ 1         ┆ … ┆ Yellow    ┆ Manhattan ┆ Upper     ┆ Yellow   │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ Zone      ┆           ┆ East Side ┆ Zone     │
│           ┆ 00:04:45  ┆ 00:19:58  ┆           ┆   ┆           ┆           ┆ North     ┆          │
│ 2         ┆ 2024-02-0 ┆ 2024-02-0 ┆ 1         ┆ … ┆ Yellow    ┆ Manhattan ┆ Washingto ┆ Boro     │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ Zone      ┆           ┆ n Heights ┆ Zone     │
│           ┆ 00:56:31  ┆ 01:10:53  ┆           ┆   ┆           ┆           ┆ North     ┆          │
│ 2         ┆ 2024-02-0 ┆ 2024-02-0 ┆ 2         ┆ … ┆ Airports  ┆ Manhattan ┆ World     ┆ Yellow   │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆ Trade     ┆ Zone     │
│           ┆ 00:07:50  ┆ 00:43:12  ┆           ┆   ┆           ┆           ┆ Center    ┆          │
│ 1         ┆ 2024-02-0 ┆ 2024-02-0 ┆ 1         ┆ … ┆ Yellow    ┆ Manhattan ┆ Midtown   ┆ Yellow   │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ Zone      ┆           ┆ North     ┆ Zone     │
│           ┆ 00:01:49  ┆ 00:10:47  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ 2024-02-0 ┆ 2024-02-0 ┆ 1         ┆ … ┆ Yellow    ┆ Manhattan ┆ East      ┆ Yellow   │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ Zone      ┆           ┆ Village   ┆ Zone     │
│           ┆ 00:37:35  ┆ 00:51:15  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
rides_df_raw.shape

(6590154, 25)

## Data Exploration

In [6]:
rides_df_raw.describe()

shape: (9, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ vendor_id ┆ tpep_pick ┆ tpep_drop ┆ … ┆ pu_servic ┆ do_boroug ┆ do_zone   ┆ do_servi │
│ ---       ┆ ---       ┆ up_dateti ┆ off_datet ┆   ┆ e_zone    ┆ h         ┆ ---       ┆ ce_zone  │
│ str       ┆ f64       ┆ me        ┆ ime       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆           ┆ str      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 6.590154e ┆ 6590154   ┆ 6590154   ┆ … ┆ 6590154   ┆ 6590154   ┆ 6590154   ┆ 6590154  │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 1.756811  ┆ 2024-03-0 ┆ 2024-03-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 2 23:29:0 ┆ 2 23:45:2 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 8.306262  ┆ 9.766303  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 0.430632  ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ min       ┆ 1.0       ┆ 2002-12-3 ┆ 2002-12-3 ┆ … ┆ Airports  ┆ Bronx     ┆ Allerton/ ┆ Airports │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆           ┆ Pelham    ┆          │
│           ┆           ┆ 22:17:10  ┆ 22:42:24  ┆   ┆           ┆           ┆ Gardens   ┆          │
│ 25%       ┆ 2.0       ┆ 2024-02-1 ┆ 2024-02-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 6         ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 23:06:24  ┆ 23:22:02  ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ 2.0       ┆ 2024-03-0 ┆ 2024-03-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 3         ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 14:05:02  ┆ 14:23:32  ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 2.0       ┆ 2024-03-1 ┆ 2024-03-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 12:36:18  ┆ 12:54:35  ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 6.0       ┆ 2024-04-0 ┆ 2024-04-0 ┆ … ┆ Yellow    ┆ Unknown   ┆ Yorkville ┆ Yellow   │
│           ┆           ┆ 1         ┆ 2         ┆   ┆ Zone      ┆           ┆ West      ┆ Zone     │
│           ┆           ┆ 00:34:55  ┆ 18:08:46  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
rides_df_raw.select(pl.all().null_count()/ pl.len())

shape: (1, 25)
┌───────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ vendor_id ┆ tpep_picku ┆ tpep_drop ┆ passenger ┆ … ┆ pu_servic ┆ do_boroug ┆ do_zone ┆ do_servic │
│ ---       ┆ p_datetime ┆ off_datet ┆ _count    ┆   ┆ e_zone    ┆ h         ┆ ---     ┆ e_zone    │
│ f64       ┆ ---        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64     ┆ ---       │
│           ┆ f64        ┆ ---       ┆ f64       ┆   ┆ f64       ┆ f64       ┆         ┆ f64       │
│           ┆            ┆ f64       ┆           ┆   ┆           ┆           ┆         ┆           │
╞═══════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ 0.0       ┆ 0.0        ┆ 0.0       ┆ 0.092835  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0     ┆ 0.0       │
└───────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

In [ ]:
cells_with_null = ["passenger_count", "rate_code_id", "store_and_fwd_flag", "congestion_surcharge", "airport_fee"]
rides_df_raw.select(
    pl.all_horizontal(pl.col(cells_with_null).is_null
)

shape: (1, 1)
┌─────────────────┐
│ passenger_count │
│ ---             │
│ f64             │
╞═════════════════╡
│ 0.092835        │
└─────────────────┘

### Plots of the target distribution

In [13]:
import hvplot.polars

In [14]:
rides_df_raw.hvplot.hist("tip_amount", bins=5000, xlim=(-1, 50))

:Histogram   [tip_amount]   (Count)